### ISSUE TITLE
Big Sur

### ISSUE THREAD

**Issue by revjkramer** [chris1111/USB-Wireless-Utility#14]
Is there a way to get this working for macOS 11 (Big Sur)? I pulled this pkg using pacifist it looks lit was last updated to run on El Capitan. I also tried your panel v2. It allows me to install, scan, but won't connect. It connects for like 5 seconds and then disconnects.

**Comment by chris1111** [comment]
Why open another issue for the same problem

the way is possible with the prefpane utility you need find on google how to make BS as read in write system using snapshot
But the drivers not working good

**Comment by pjfa** [comment]
no solution yet ?

**Comment by chris1111** [comment]
> no solution yet ?

No drivers and utility  Obsolete
