### ISSUE TITLE
not wotk at usb 2.0 high sierra 

### ISSUE THREAD

**Issue by HFAsif** [chris1111/USB-Wireless-Utility#15]
when i connect usb wirless 802.11n on high sierra it popup the site servey , but in side no list of wifi/ please help my usb wirless 3.0 but my laptop port 2.0 ,

**Comment by chris1111** [comment]
what is the adapter Brand and model?

**Comment by HFAsif** [comment]
brand is LB Link 802.11n . usb 3.0 , but my laptop port is 2.0

**Comment by chris1111** [comment]
Thats not a brand and not a model

**Comment by HFAsif** [comment]
if i have tp link 802.11n usb 3.0 that will works in 2.0 port ?

**Comment by chris1111** [comment]
Which TP Link model? 802.11n its not a model
