### ISSUE TITLE
There should be some way to quit the menu item

### ISSUE THREAD

**Issue by ApopheniaPays-psnl** [chris1111/USB-Wireless-Utility#17]
At this point, with seemingly every app feeling entitled to a permanent spot on my menu bar, space up there is at a premium. I only need this app once every few weeks, it's kind of a pain to have to uninstall entirely to keep the menu item out of my menu bar when I don't need it.

**Comment by chris1111** [comment]
Go to System Preferences /User / Login Item
Disable at Login

**Comment by ApopheniaPays-psnl** [comment]
Thanks, but that requires me to restart my computer to quit it, then? I'd still prefer a "quit menu extra" option to have to log out or restart to quit one app.

**Comment by chris1111** [comment]
log out thats it
The app not showing any more in the menue bar
