### ISSUE TITLE
Change Country code

### ISSUE THREAD

**Issue by ealopezg** [chris1111/USB-Wireless-Utility#2]
Hello, I'm using this driver for my mini usb wifi card in macOS Mojave. I'm from Chile and my university's Wifi network is using the Channel 12. The problem is I can't connect to the network because the SSID does not show on the Wireless Utility. Do you know how to change the country code on the driver to connect to networks that is using Channel 12?.
Thanks

**Comment by chris1111** [comment]
Sorry late reply
You can Referring you to the PDF on Management to this section (Join a Hidden network Wifi)
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu643.png)
