### ISSUE TITLE
App wont open

### ISSUE THREAD

**Issue by DedoGamingONE** [chris1111/USB-Wireless-Utility#4]
The app wont open at all.

**Comment by chris1111** [comment]
on which macOS and which usb adapter

**Comment by DedoGamingONE** [comment]
Mojave 10.14.1 and th TP-Link Archer T2UH

**Comment by chris1111** [comment]
10.14.1 maybe its time to Update 10.14.5
I have a TP-Link Archer T2UH with no issue on 10.14.5

**Comment by DedoGamingONE** [comment]
I have a Ryzen Hackinstosh so i cant just "Update to 10.24.5"

**Comment by chris1111** [comment]
> I have a Ryzen Hackinstosh so i cant just "Update to 10.24.5"

Ok that's the Issue  this app is 32Bit and not woking on a Ryzen Only 64Bit run on Ryzen CPU

**Comment by DedoGamingONE** [comment]
Is there a 64bit version of this app? Or a bypass or something

**Comment by chris1111** [comment]
> Is there a 64bit version of this app? Or a bypass or something

No The only thing working in Mojave for now for Your Adapter is this 
https://github.com/chris1111/USB-Wireless-UtilityPrefPane

try and let me know

**Comment by chris1111** [comment]
> Is there a 64bit version of this app? Or a bypass or something

No this app is no longer update by the developper
You can try this app, its for Catalina but its work on Mojave
Try and let me know

https://github.com/chris1111/WIFI-Dlink-Catalina-Panel

**Comment by DedoGamingONE** [comment]
Perfect! Thanks for your help

**Comment by DedoGamingONE** [comment]
I do have one problem though. My internet speed is SUPER slow. I usually get 100 MB’s but now I get less than 1 MB’s

**Comment by chris1111** [comment]
> I do have one problem though. My internet speed is SUPER slow. I usually get 100 MB’s but now I get less than 1 MB’s

Ok thanks for test 
Its a Beta installer so is to be better support
